apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cassandra-snapshot
spec:
  schedule: "*/1 * * * *"  
  jobTemplate:             
    spec:
      template:
        metadata:
          labels:          
            parent: "cronjobpi"
        spec:
          containers:
          - name: cassandra-snapshot
            image: cassandra:3
            command: ["nodetool", "-h", "cassandra-cluster-0", "status"]
          restartPolicy: OnFailure 
