apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra-cluster
  labels:
    app: cassandra-cluster
spec:
  serviceName: cassandra-cluster
  replicas: 3
  selector:
    matchLabels:
      app: cassandra-cluster
  template:
    metadata:
      labels:
        app: cassandra-cluster
    spec:
      terminationGracePeriodSeconds: 1800
      containers:
      - name: cassandra-cluster
        image: bitnami/cassandra:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 7000
          name: intra-node
        - containerPort: 7001
          name: tls-intra-node
        - containerPort: 7199
          name: jmx
        - containerPort: 9042
          name: cql
        resources:
          limits:
            cpu: "500m"
            memory: 1Gi
          requests:
            cpu: "500m"
            memory: 1Gi
        env:
          - name: MAX_HEAP_SIZE
            value: 512M
          - name: HEAP_NEWSIZE
            value: 100M
          - name: CASSANDRA_SEEDS
            value: "cassandra-cluster-0.cassandra-cluster.nos-automation.svc.cluster.local"
          - name: CASSANDRA_CLUSTER_NAME
            value: "cassandra-cluster"
          - name: CASSANDRA_DATACENTER
            value: "DC1"
          - name: CASSANDRA_RACK
            value: "Rack1"
          - name: CASSANDRA_ENDPOINT_SNITCH
            value: "GossipingPropertyFileSnitch"
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        # These volume mounts are persistent. They are like inline claims,
        # but not exactly because the names need to match exactly one of
        # the stateful pod volumes.
        volumeMounts:
        - name: cassandra-data
          mountPath: /bitnami
        #- name: cassandra-config
        #  mountPath: /bitnami/cassandra/conf/
      #volumes:
      #  - name: cassandra-config
      #    configMap:
      #      name: cassandra-config
  # These are converted to volume claims by the controller
  # and mounted at the paths mentioned above.
  # do not use these in production until ssd GCEPersistentDisk or other ssd pd
  volumeClaimTemplates:
  - metadata:
      name: cassandra-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: dynamic-nfs
      resources:
        requests:
          storage: 1Gi
