apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra-migrator
  labels:
    app: cassandra-migrator
spec:
  serviceName: cassandra-migrator
  replicas: 3
  selector:
    matchLabels:
      app: cassandra-migrator
  template:
    metadata:
      labels:
        app: cassandra-migrator
    spec:
      terminationGracePeriodSeconds: 1800
      containers:
      - name: cassandra-migrator
        image: quay.io/factory2/cassandra:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 7000
          name: intra-node
        - containerPort: 7001
          name: tls-intra-node
        - containerPort: 7199
          name: jmx
        - containerPort: 9042
          name: cql
        - containerPort: 7070
          name: metrics
        resources:
          limits:
            cpu: 1
            memory: 4Gi
          requests:
            cpu: 1
            memory: 4Gi
        lifecycle:
          preStop:
            exec:
              command: 
              - /bin/sh
              - -c
              - nodetool drain
        env:
          - name: MAX_HEAP_SIZE
            value: 1024M
          - name: HEAP_NEWSIZE
            value: 200M
          - name: CASSANDRA_SEEDS
            value: "cassandra-migrator-0.cassandra-migrator.nos-automation.svc.cluster.local"
          - name: CASSANDRA_CLUSTER_NAME
            value: "cassandra-migrator"
          - name: CASSANDRA_ENDPOINT_SNITCH
            value: "GossipingPropertyFileSnitch"
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        # These volume mounts are persistent. They are like inline claims,
        # but not exactly because the names need to match exactly one of
        # the stateful pod volumes.
        volumeMounts:
        - name: cassandra-migrator-data
          mountPath: /var/lib/cassandra
        - name: cassandra-migrator-config
          mountPath: /custom/cassandra/config/
      volumes:
        - name: cassandra-migrator-config
          configMap:
            name: cassandra-migrator-config
  volumeClaimTemplates:
  - metadata:
      name: cassandra-migrator-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: dynamic-nfs
      resources:
        requests:
          storage: 50Gi
