apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra-cluster
  name: cassandra-cluster
spec:
  clusterIP: None
  ports:
  - name: 'cql'
    port: 9042
  - name: 'metrics'
    port: 7070
  selector:
    app: cassandra-cluster
